### ISSUE TITLE
配置对应环境运行缺失libcufft.so.11和libnvJitLink.so.12

### ISSUE THREAD

**Issue by qulishen** [ykdai/Flare7K#14]
python3 evaluate.py --input result/blend/ --gt dataset/Flare7Kpp/test_data/real/gt/ --mask dataset/Flare7Kpp/test_data/real/mask/

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/flare/lib/python3.9/site-packages/torch/__init__.py", line 174, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/ubuntu/anaconda3/envs/flare/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcufft.so.11: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/qls/Flare7K/evaluate.py", line 6, in <module>
    from torchvision.transforms import ToTensor
  File "/home/ubuntu/anaconda3/envs/flare/lib/python3.9/site-packages/torchvision/__init__.py", line 5, in <module>
    import torch
  File "/home/ubuntu/anaconda3/envs/flare/lib/python3.9/site-packages/torch/__init__.py", line 234, in <module>
    _load_global_deps()
  File "/home/ubuntu/anaconda3/envs/flare/lib/python3.9/site-packages/torch/__init__.py", line 195, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/ubuntu/anaconda3/envs/flare/lib/python3.9/site-packages/torch/__init__.py", line 161, in _preload_cuda_deps
    ctypes.CDLL(lib_path)
  File "/home/ubuntu/anaconda3/envs/flare/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvJitLink.so.12: cannot open shared object file: No such file or directory

**Comment by ykdai** [comment]
This problem occurs in pytorch rather than our code. You may need to reinstall your pytorch and match the pytroch version with your cuda version. You can search the error: `OSError: libcufft.so.11: cannot open shared object file: No such file or directory` for more details.
