### ISSUE TITLE
KeyError: "No object named 'ExampleModel' found in 'model' registry!"

### ISSUE THREAD

**Issue by sujiajiaa** [ykdai/Flare7K#3]
您好，我在文件夹中没有找到 *_model.py 文件，请问可以提供一下吗？谢谢

Traceback (most recent call last):
  File "F:/pythonProject/Flare7K-main/basicsr/train.py", line 213, in <module>
    train_pipeline(root_path)
  File "F:/pythonProject/Flare7K-main/basicsr/train.py", line 122, in train_pipeline
    model = build_model(opt)
  File "F:\pythonProject\Flare7K-main\basicsr\models\__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "F:\pythonProject\Flare7K-main\basicsr\utils\registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'ExampleModel' found in 'model' registry!"

**Comment by ykdai** [comment]
You can run the code in 'deflare.ipynb' for inference directly without the '*_model.py' file. We just use the BasicSR module for training, and the training code (with *_model.py module) will be released soon.

**Comment by sujiajiaa** [comment]
> 

感谢，非常期待您的更新。
