### ISSUE TITLE
Can I get your help on code execution?

### ISSUE THREAD

**Issue by staraaaa** [ykdai/Flare7K#6]
Excuse me, I always get the following error when debugging code locally according to your requirements

Name Flare_Pair_Loader is not found, use name: Flare_Pair_Loader_basicsr!
Traceback (most recent call last):
  File "basicsr/train.py", line 215, in &lt;module&gt;
    train_pipeline(root_path)
  File "basicsr/train.py", line 120, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "basicsr/train.py", line 35, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
  File "/home/cvgroup/anaconda3/envs/flare/lib/python3.7/site-packages/basicsr/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "/home/cvgroup/anaconda3/envs/flare/lib/python3.7/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'Flare_Pair_Loader' found in 'dataset' registry!"
If I could get your help, I would be extremely grateful！

**Comment by ykdai** [comment]
Is there a flare7k_dataset.py in your 'home/cvgroup/anaconda3/envs/flare/lib/python3.7/site-packages/basicsr/data/' path? Seems you load the basicsr from the anaconda path, and not from the project path.

**Comment by ykdai** [comment]
Hello, I have updated setup files in the root directory. If you still have not fixed this problem, you may try the Installation method in README.

**Comment by staraaaa** [comment]
Thank you very much for your help. It means a lot to me！
